<!-- JS here -->
<script src="{{ asset('evente-assets/js/vendor/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/imagesloaded.pkgd.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/jquery.odometer.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/jquery.appear.js') }}"></script>
<script src="{{ asset('evente-assets/js/gsap.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/jquery.countdown.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/wow.min.js') }}"></script>
<script src="{{ asset('evente-assets/js/main.js') }}"></script>